server:
  ip: 192.168.0.243
  port: 3001
eureka:
  enabled: true
  client:
    serviceUrl:
      defaultZone: http://192.168.0.126:1000/eureka/

spring:
  datasource:
    name: test

    # 设置下面的三项以正确连接数据库
    # 加上?后面的可以解决不能查询出中文的问题
    url: jdbc:mysql://192.168.0.130:3306/db_center?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 11111111

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    multipart:
      enabled: true
      max-file-size: 52428800
      max-request-size: 52428800

# 库表套件
sls-db-kit.ip: 192.168.0.121
sls-db-kit.port: 6000

# 文件套件
sls-file-kit.ip: 192.168.0.121
sls-file-kit.port: 7000

# 服务套件
sls-service-kit.ip: 192.168.0.121
sls-service-kit.port: 8000

#策略服务
sls-policy.ip: 192.168.0.121
sls-policy.port: 4000

sls.FILE_PATH: C:/sls/filePath