server:
  ip: slsserver
  port: 3000
eureka:
  enabled: true
  client:
    serviceUrl:
      defaultZone: http://slsserver:1000/eureka/

spring:
  datasource:
    name: test

    # 设置下面的三项以正确连接数据库
    # 加上?后面的可以解决不能查询出中文的问题
    url: jdbc:mysql://slsmysqlcenter:3306/db_center?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 11111111

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    multipart:
      enabled: true
      max-file-size: 52428800
      max-request-size: 52428800

#策略服务
sls-policy.ip: slsgateway
sls-policy.port: 2000

sls.FILE_PATH: C:/sls/filePath
