# Notice:
# 在Linux下，如果使用1024以下的端口则需要root权限
#
server.port: 7000
#eureka.instance.hostname: localhost

eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false
# eureka.client.serviceUrl.defaultZone: http://slsserver:${server.port}/eureka/
eureka.client.serviceUrl.defaultZone: http://127.0.0.1:${server.port}/eureka/
