spring.profiles.active: local

spring:
  application:
    name: task-system

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.microcore.center.model, com.rainyhon.common.model

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#debug: true
logging:
  path: logs/${spring.application.name}
  level: debug

#登陆jwt 变量设置
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route.authentication.path: /auth

security.user.name: root
security.user.password: root
security.basic.enabled: false
spring.cache.type: ehcache
spring.cache.ehcache.config: classpath:ehcache.xml