server:
  port: 7010

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7000/eureka/

security:
  basic:
    enabled: false
  ignored: /**

sls:
  FILE_PATH: /filePath

redis:
  server: 127.0.0.1
  port: 6379