spring.profiles.active: local

spring:
  application:
    name: auth-server

#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.microcore.auth.model

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#debug: true
logging:
  path: logs/${spring.application.name}

#区块链公私钥对：004
BLOCK_ChAIN_SERVICE:
  privateKey: 668be5705fd0779bce8b2e8d64e935f203750578d2d448969f3204ced905562d
  publicKey: 04bd91600c6107acb5fe8bc5d025adb339344101d1c54f010b65503b916efc8bf34ff98e9aa629631b82889b4c5e6f71f8235a9209acb1376139b13ef3a56c2701
  ip: 192.168.0.30
#登陆jwt 变量设置
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route.authentication.path: /auth