server:
  port: 7100
eureka:
   client:
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/, http://peer2:7002/eureka/, http://peer3:7003/eureka/

spring:
  datasource:
    name: test

    # 设置下面的三项以正确连接数据库
    # 加上?后面的可以解决不能查询出中文的问题
    url: jdbc:mysql://127.0.0.1:3306/psm?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    multipart:
      enabled: true
      max-file-size: 52428800
      max-request-size: 52428800

# user.face.image.directory: D:/FaceImages
sls.FILE_PATH: D:/FaceImages

rabbit:
  # server.ip: 192.168.1.140
  server.ip: 127.0.0.1
  server.port: 5672
  username: admin
  password: 11111111

nvr.device:
  ip: 192.168.254.2
  port: 8000

login:
  username: admin
  password: rain@1234

face.api:
  ip: 127.0.0.1
  port: 8889

summary:
  task:
    interval: 60000

redis:
  server: 127.0.0.1
  port: 6379

#logging.level: debug

